import { useMemo, useState } from "react";

type Mode = "multiply" | "divide";
type Stage = "tables" | "table" | "practice";
const makeRows=(t:number,m:Mode)=>Array.from({length:9},(_,i)=>{const n=i+1;return m==="multiply"?{a:t,b:n,c:t*n}:{a:t*n,b:t,c:n}});

export default function ReviewScreen({onBack}:{onBack:()=>void}){
 const [stage,setStage]=useState<Stage>("tables"),[table,setTable]=useState(2),[mode,setMode]=useState<Mode>("multiply");
 const rows=useMemo(()=>makeRows(table,mode),[table,mode]);
 if(stage==="tables") return <main className="review-screen"><header className="review-header"><button className="back-review" onClick={onBack}>← Bản đồ</button><div><div className="eyebrow">📚 HỌC LẠI</div><h1>Ôn tập bảng cửu chương</h1></div></header><section className="review-home"><div className="review-hero">🧠</div><h2>Chọn bảng muốn ôn</h2><p>Chọn từ bảng 2 đến bảng 9.</p><div className="table-picker">{Array.from({length:8},(_,i)=>i+2).map(n=><button key={n} onClick={()=>{setTable(n);setStage("table")}}><span>{n}</span><small>Bảng {n}</small></button>)}</div></section></main>;
 if(stage==="practice") return <Practice table={table} mode={mode} onBack={()=>setStage("table")}/>;
 return <main className="review-screen"><header className="review-header"><button className="back-review" onClick={()=>setStage("tables")}>← Chọn bảng</button><div className="review-title"><span className="big-table-number">{table}</span><div><div className="eyebrow">BẢNG {table}</div><h1>Ôn tập bảng {table}</h1></div></div></header><section className="table-study"><div className="mode-tabs"><button className={mode==="multiply"?"active":""} onClick={()=>setMode("multiply")}>✖️ Nhân</button><button className={mode==="divide"?"active":""} onClick={()=>setMode("divide")}>➗ Chia</button></div><div className="study-content"><div className="table-card"><div className="table-card-head"><span>{mode==="multiply"?`Bảng nhân ${table}`:`Bảng chia ${table}`}</span><span>9 phép tính</span></div><div className="study-rows">{rows.map((r,i)=><div className="study-row" key={i}><span>{i+1}</span><strong>{r.a} {mode==="multiply"?"×":"÷"} {r.b} = {r.c}</strong><span>✓</span></div>)}</div></div><div className="practice-intro"><div className="practice-icon">✏️</div><h2>Sẵn sàng luyện tập?</h2><p>Game sẽ che ngẫu nhiên số thứ nhất, số thứ hai hoặc kết quả. Hãy điền số còn thiếu.</p><button className="practice-btn" onClick={()=>setStage("practice")}>🎯 Luyện tập bảng {table}</button></div></div></section></main>;
}

function Practice({table,mode,onBack}:{table:number;mode:Mode;onBack:()=>void}){
 const [round,setRound]=useState(0),[value,setValue]=useState(""),[checked,setChecked]=useState(false),[correct,setCorrect]=useState(0),[done,setDone]=useState(false);
 const rows=makeRows(table,mode),r=rows[round],hidden=round%3,expected=hidden===0?r.a:hidden===1?r.b:r.c,isCorrect=checked&&Number(value)===expected;
 const submit=()=>{if(!value||checked)return;setChecked(true);if(Number(value)===expected)setCorrect(x=>x+1)};
 const next=()=>{if(round===8){setDone(true);return}setRound(x=>x+1);setValue("");setChecked(false)};
 if(done){const stars=correct>=8?3:correct>=6?2:correct>=4?1:0;return <main className="review-screen practice-screen"><section className="practice-result"><div className="result-icon">🏆</div><div className="eyebrow">LUYỆN TẬP HOÀN THÀNH</div><h1>Bảng {mode==="multiply"?"nhân":"chia"} {table}</h1><div className="stars-big">{"★".repeat(stars)}{"☆".repeat(3-stars)}</div><p>Bạn trả lời đúng <strong>{correct}/9</strong> câu.</p><div className="result-actions"><button onClick={()=>{setRound(0);setValue("");setChecked(false);setCorrect(0);setDone(false)}}>🔁 Luyện lại</button><button className="secondary" onClick={onBack}>← Về bảng</button></div></section></main>}
 const part=(v:number,h:boolean)=>(h?<input autoFocus inputMode="numeric" disabled={checked} className={`missing-input ${checked?(isCorrect?"input-correct":"input-wrong"):""}`} value={value} onChange={e=>setValue(e.target.value.replace(/\D/g,"").slice(0,3))}/>:<span className="fixed-number">{v}</span>);
 return <main className="review-screen practice-screen"><header className="review-header"><button className="back-review" onClick={onBack}>← Bảng {table}</button><div><div className="eyebrow">🎯 LUYỆN TẬP</div><h1>Bảng {mode==="multiply"?"nhân":"chia"} {table}</h1></div><div className="practice-counter">Câu {round+1}/9 · ✓ {correct}</div></header><section className="practice-content"><div className="practice-card"><div className="practice-hint">Điền số còn thiếu</div><div className="missing-equation">{part(r.a,hidden===0)}<span>{mode==="multiply"?"×":"÷"}</span>{part(r.b,hidden===1)}<span>=</span>{part(r.c,hidden===2)}</div><div className={`practice-feedback ${checked?(isCorrect?"correct":"wrong"):""}`}>{!checked?"💡 Hãy suy nghĩ thật kỹ!":isCorrect?"🎉 Chính xác!":"❌ Chưa đúng. Đáp án: "+expected}</div>{!checked?<button className="check-btn" disabled={!value} onClick={submit}>Kiểm tra ✓</button>:<button className="check-btn" onClick={next}>{round===8?"Hoàn thành 🏆":"Câu tiếp theo →"}</button>}</div></section></main>;
}
